gauss_jacobi(xn, yn, zn, wn, x0, y0, z0, w0, n_iterations):=(
    for i:0 thru n_iterations do (
        x0: xn(x0),
        y0: yn(y0),
        z0: zn(z0),
        w0: wn(w0),
        print("x", x0),
        print("y", y0),
        print("z", z0),
        print("w", w0),
        print(" ")
    )
)$

xn(x):=(215.0-4.0*y0-6.0*z0-5.0*w0)/200.0;
yn(y):=(180.0-10.0*x0-10.0*z0-10.0*w0)/150.0;
zn(z):=(118.0-3.0*x0-5.0*y0-10.0*w0)/100.0;
wn(w):=(90.0-2.0*x0-5.0*y0-5*z0)/80;